[package]
name = "stock_verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
time = "0.3.37"
html_editor = "0.7.0"
structopt = { version = "0.3", default-features = false}
tokio = "1.43.0"
yahoo_finance_api = "2.4.0"
